version: "3.9"
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/code
    environment:
      FLASK_DEBUG: True
    depends_on:
      - redis
  redis:
    image: "redis:latest"
    container_name: "redis"
    ports:
      - "6379:6379"